bc:
  strength: 8

token:
  ttl: 300

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/product_move
    password:

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    password:
    port: 6379

  mail:
    username: vlxx2022tv@gmail.com
    password: qxzdvjbeetfzoqwk

server:
  address: localhost
  port: 3001
  servlet:
    context-path: /backend

